### PR TITLE
Update eslint to v8

### PR DESCRIPTION
**Pull request by 0xkenta**
Update eslint to 8.1.0

This Updete of eslint needs updates of the other 3 packages(@typescript-eslint/eslint-plugin, @typescript-eslint/parser and eslint-plugin-functional).

There were some errors with the update of eslint-plugin-functional, so I moved functional/no-return-void from rules of overrides into rules. In addition to that, I had @typescript-eslint/no-loss-of-precision errors. In this case, it was impossible to resolve without adding a new rule because of the constant variables in the code. So I added @typescript-eslint/no-loss-of-precision into the rules.

This PR must resolve all 3 bot PRs that you see in PRs because I updated all 3 packages which bot PRs have.

### CODE REVIEW

**Comment by hhatto** [comment]
@0xkenta 

Thanks for contribution.
I'm sorry to keep repeating this, but could you please resolve the conflict?


When I tried it on the following branch, I got the following warning when I ran yarn lint:

https://github.com/dev-protocol/dev-kit-js/tree/update-eslint-to-v8-2

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

Please only submit bug reports when using the officially supported version.

=============
```

Does this seem to be a problem?

**Comment by 0xkenta** [comment]
Thank you for your comment.

I'm sorry to keep repeating this, but could you please resolve the conflict? Did you mention it somewhere? I did not see it, sorry about that. Please write on Discord if you have no response from me.

Now it must be OK. Like you see I added warnOnUnsupportedTypeScriptVersion into parserOptions because it works well although the typescripts version is not officially supported. I will work on this again if you have a problem with that.

**Comment by hhatto** [comment]
There was another conflict, and I've resolved it.

**Review by hhatto — APPROVED** [review]
LGTM 👍

**Pull request merged**
